export {default as Courses} from '../pages/Courses'
export {default as CourseDetail} from '../pages/CourseDetail'
export {default as LessonDetail} from '../pages/LessonDetail'
export {default as CourseDiscussion} from '../pages/CourseDiscussion'
export {default as CaseStudyGallery} from '../pages/CaseStudyGallery'
export {default as CaseStudyDetail} from '../pages/CaseStudyDetail'
export {default as IndigenousMap} from '../pages/IndigenousMap'
export {default as Tribe} from '../pages/Tribe'
export {default as About} from '../pages/About'
export {default as StudyGallery} from '../pages/StudyGallery'
export {default as SubmitCaseStudy} from '../pages/SubmitCaseStudy.jsx'
// export {default as ProtectedRoute} from './pages/ProtectedRoute'
export {default as Dashboard} from '../pages/Dashboard'
export {default as Signup} from '../pages/Signup'
export {default as Login} from '../pages/Login'